### ISSUE TITLE
Debug Option don't work right

### ISSUE THREAD

**Issue by suerion** [Kotori316/FluidTank2#662]
Hey, i had in the fluidtank config, the debug setting dissabled, but it log the debuginfo in the console

![image](https://github.com/user-attachments/assets/786d11fc-12e1-406f-adcf-34b03d125fd6)

**Comment by suerion** [comment]
Oh, sorry, i'm on 1.21.1 Fabric

**Comment by suerion** [comment]
`[23:24:16] [main/ERROR]: Failed to initialize DebugLogging.LOGGER. See the log for detail. Uri: jar:file:/C:/Users/********/Desktop/Testserver/Minecraft/mods/largefluidtank-fabric-21.1.6.jar!/fluidtank-log4j2.xml, Context: null`

**Comment by Kotori316** [comment]
It's intended. For the error message, I can't reproduce in my prod env.

**Comment by suerion** [comment]
@Kotori316 

Again:

```
ERROR StatusConsoleListener There was a problem initializing the LoggerContext [fluidtank-config] using configuration at [jar:file:/C:/Users/Bremo/Desktop/Testserver/Minecraft/mods/largefluidtank-fabric-21.1.7.jar!/fluidtank-log4j2.xml].
 java.lang.IllegalStateException: Unable to register Log4j shutdown hook because JVM is shutting down.
        at knot//org.apache.logging.log4j.core.LoggerContext.setUpShutdownHook(LoggerContext.java:324)
        at knot//org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:284)
        at knot//org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:281)
        at knot//org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:173)
        at knot//org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:128)
        at knot//com.kotori316.fluidtank.DebugLogging$.<clinit>(DebugLogging.scala:23)
        at knot//com.kotori316.fluidtank.DebugLogging.LOGGER(DebugLogging.scala)
        at knot//com.kotori316.fluidtank.recipe.TierRecipe.<init>(TierRecipe.java:63)
        at knot//com.kotori316.fluidtank.recipe.TierRecipe$Serializer.createInstance(TierRecipe.java:235)
        at knot//com.kotori316.fluidtank.recipe.TierRecipe$Serializer.createInstanceInternal(TierRecipe.java:239)
        at knot//com.mojang.serialization.DataResult$Instance.ap2(DataResult.java:434)
        at knot//com.mojang.serialization.codecs.RecordCodecBuilder$Instance$3.decode(RecordCodecBuilder.java:246)
        at knot//com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107)
        at knot//com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$3(KeyDispatchCodec.java:54)
        at knot//com.mojang.serialization.DataResult$Success.flatMap(DataResult.java:201)
        at knot//com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$4(KeyDispatchCodec.java:46)
        at knot//com.mojang.serialization.DataResult$Success.flatMap(DataResult.java:201)
        at knot//com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:45)
        at knot//com.mojang.serialization.MapDecoder.lambda$compressedDecode$1(MapDecoder.java:52)
        at knot//com.mojang.serialization.DataResult$Success.flatMap(DataResult.java:201)
        at knot//com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
        at knot//com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:158)
        at knot//com.mojang.serialization.Decoder.parse(Decoder.java:18)
        at knot//net.minecraft.class_1863.method_20705(class_1863.java:62)
        at knot//net.minecraft.class_1863.method_18788(class_1863.java:35)
        at knot//net.minecraft.class_4080.method_18790(class_4080.java:13)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at knot//net.minecraft.class_4014.method_18365(class_4014.java:69)
        at knot//net.minecraft.class_156.method_43498(class_156.java:1024)
        at knot//net.minecraft.class_156.method_43499(class_156.java:1012)
        at knot//net.minecraft.server.Main.main(Main.java:182)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
Caused by: java.lang.IllegalStateException: Cannot add new shutdown hook as this is not started. Current state: STOPPED
        at knot//org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.addShutdownCallback(DefaultShutdownCallbackRegistry.java:137)
        at knot//org.apache.logging.log4j.core.impl.Log4jContextFactory.addShutdownCallback(Log4jContextFactory.java:411)
        at knot//org.apache.logging.log4j.core.LoggerContext.setUpShutdownHook(LoggerContext.java:305)
        ... 36 more
[21:16:26 ERROR] [main]: [FluidTankCommon] Failed to initialize DebugLogging.LOGGER. See the log for detail. Uri: jar:file:/C:/Users/Bremo/Desktop/Testserver/Minecraft/mods/largefluidtank-fabric-21.1.7.jar!/fluidtank-log4j2.xml, Context: null
```

**Comment by Kotori316** [comment]
Just ignore the message. I don't know the reason why the error message shows. It never affects the actual game play.
